version: "3.1"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app
    env_file:
      - ./.env
    ports:
      - 8443:8443
    logging:
      options:
        max-size: "1M"
        max-file: "10"
